name: WebAssembly

on: [push]

jobs:
  Vcpkg:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:3.1.74
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: "Run apt"
        run: |
          sudo apt update -y
          sudo apt install -y python3 pkg-config autoconf automake autoconf-archive file

      - name: "Run vcpkg(wasm32-emscripten)"
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgDirectory: "/usr/local/share/vcpkg" # VCPKG_INSTALLATION_ROOT
          runVcpkgInstall: true
          vcpkgJsonGlob: "cmake/vcpkg.json"
          vcpkgConfigurationJsonGlob: "cmake/vcpkg-configuration.json"
        env:
          VCPKG_INSTALLED_DIR: "${{ github.workspace }}/.build"
          VCPKG_DEFAULT_TRIPLET: "wasm32-emscripten"

      - name: "Detect protoc"
        id: protoc-detect
        run: |
          set -e -x
          export PROTOC_DIR="$(pwd)/.build/x64-linux/tools/protobuf"
          export PATH="$PROTOC_DIR:$PATH"
          protoc --version
          echo "protoc_path=$(which protoc)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: "Run compile_schema.py"
        run: |
          set -e -x
          export FLATC_DIR="$(pwd)/.build/x64-linux/tools/flatbuffers"
          export PATH="$FLATC_DIR:$PATH"
          flatc --version
          python3 onnxruntime/core/flatbuffers/schema/compile_schema.py --flatc "$(which flatc)"
          python3 onnxruntime/lora/adapter_format/compile_schema.py --flatc "$(which flatc)"
        shell: bash

      - name: "Run build.py"
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          python3 ./tools/ci_build/build.py --allow_running_as_root \
            --build_dir ./build \
            --build_wasm \
            --skip_submodule_sync \
            --cmake_extra_defines "CMAKE_TOOLCHAIN_FILE:FILEPATH=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" \
            --cmake_extra_defines "VCPKG_TARGET_TRIPLET=wasm32-emscripten" \
            --cmake_extra_defines "VCPKG_INSTALLED_DIR:PATH=${{ github.workspace }}/.build"
        shell: bash
